export default{
    "UAT":[
        {
            "SuperAdmin":{
             "email":"automation@yopmail.com",
             "password":"Test12!@"
            },
            "Admin":{
             "email":"procure@yopmail.com",
             "password":"Test12!@"
            }}
        ],
    "DEV":[
        {
           "SuperAdmin":{
             "email":"priyaman@yahoo.com",
             "password":"Test12!@"
            },
           "Admin":{
             "email":"procure@yopmail.com",
             "password":"Test12!@"
            }}
        ],
    "STAG":[
        {
            "SuperAdmin":{
             "email":"priyaman@yahoo.com",
             "password":"Test12!@"
            },
            "Admin":{
             "email":"procure@yopmail.com",
             "password":"Test12!@"
            }}
        ]    

    }